export const restArray = [
  {
    id: 0,
    title: 'Пицца Плюс',
    time: 50,
    rating: 4.5,
    price: 900,
    type: 'Пицца',
    image: 'pizza-plus',
  },
  {
    id: 1,
    title: 'Тануки',
    time: 50,
    rating: 4.5,
    price: 900,
    type: 'Пицца',
    image: 'tanuki',
  },
  {
    id: 2,
    title: 'FoodBand',
    time: 50,
    rating: 4.5,
    price: 900,
    type: 'Пицца',
    image: 'foodband',
  },
  {
    id: 3,
    title: 'Жадина-пицца',
    time: 50,
    rating: 4.5,
    price: 900,
    type: 'Пицца',
    image: 'jadina-pizza',
  },
  {
    id: 4,
    title: 'Точка еды',
    time: 50,
    rating: 4.5,
    price: 900,
    type: 'Пицца',
    image: 'tochka',
  },
  {
    id: 5,
    title: 'PizzaBurger',
    time: 50,
    rating: 4.5,
    price: 900,
    type: 'Пицца',
    image: 'pizza-burger',
  },
];
